development:
  adapter: postgresql
  encoding: unicode
  database: periphery_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: periphery_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: periphery_production
  pool: 5